name: Bug Report
description: Report a correctness, performance, or build/runtime bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following information to help us diagnose the issue.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear, concise description of the issue.
      placeholder: What's the bug?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Provide a minimal repro with commands to run.
      placeholder: |
        ```bash
        uv sync
        uv run python -m forge_cute_py.env_check
        uv run pytest tests/test_copy_transpose.py -k "float16 and tile_size=16"
        ```
    validations:
      required: true

  - type: input
    id: op-name
    attributes:
      label: Operation Name
      description: Which op is affected? (e.g., copy_transpose, reduce_sum, softmax_online)
      placeholder: copy_transpose
    validations:
      required: false

  - type: input
    id: op-details
    attributes:
      label: Operation Details
      description: dtype, shape(s), tile_size, dim/variant
      placeholder: "dtype=float16, shape=(1024, 1024), tile_size=16"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Logs
      description: Paste the full error or stack trace here.
      render: shell
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04, Windows 11, macOS 14"
    validations:
      required: true

  - type: input
    id: gpu
    attributes:
      label: GPU Model
      placeholder: "NVIDIA RTX 4090, A100, H100"
    validations:
      required: true

  - type: input
    id: driver
    attributes:
      label: NVIDIA Driver Version
      placeholder: "nvidia-smi output"
    validations:
      required: true

  - type: input
    id: cuda
    attributes:
      label: CUDA Toolkit Version
      placeholder: "nvcc --version output"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "python --version output"
    validations:
      required: true

  - type: input
    id: pytorch
    attributes:
      label: PyTorch Version
      placeholder: "python -c 'import torch; print(torch.__version__)' output"
    validations:
      required: true

  - type: textarea
    id: env-check
    attributes:
      label: Environment Check Output
      description: Output of `uv run python -m forge_cute_py.env_check`
      render: shell
    validations:
      required: false

  - type: textarea
    id: perf-context
    attributes:
      label: Performance or Profiling Context
      description: Benchmark command and results, ncu/nsys report (if relevant)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false
